function gquery(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',sc='.cache.html',_='/',$b='0BC7000A9D9B81D12F1B265C881B8370',ac='0C45714807EDB0767787DF56ADDACC2A',bc='0E2C42B721D73A9A04E1AE08DB406854',cc='1E0D6D95D22341BABE67916C89FE2EAD',dc='23DA4E25A9B6C883CC04D2B79575C07A',ec='3DC4DDEE6372ADFFC91E9E3B82335DD0',fc='4199921277672B9ECF55DCD57DD6FF31',gc='431EFC916FFC3A76ED27092BDF3381C6',hc='515BDD9BE55204D65A5B428FFD474DB0',ic='5BB09DA9735503AAD3652483A02847BE',jc='5EF55B1419B70F3066BBD835E18B5AC4',kc='8DF1AAB359ED57276CF776B9B86E69FA',lc='8E136B4556AC6BAD17EE6E8515D3972E',rc=':',ob='::',Ac='<script defer="defer">gquery.onInjectionDone(\'gquery\')<\/script>',hb='<script id="',rb='=',$='?',mc='AE60D68B51645BC96FC7756F4CCE8DA2',Mb='ActiveXObject',nc='B25DAB1BE33DFFCBF108ADCA793F1DDE',oc='B35BB6ACCEECA620E6A34DB247F3E87F',tb='Bad handler "',Nb='ChromeTab.ChromeFrame',pc='D095F1913B8CECB47AC168AA460EBF53',qc='D0F6751D7CE5E442A4EDD6382FAA3454',zc='DOMContentLoaded',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_gquery',kb='base',cb='baseUrl',T='begin',S='bootstrap',Lb='chromeframe',bb='clear.cache.gif',qb='content',Cb='default',_b='en',Y='end',Zb='fr',Tb='gecko',Ub='gecko1_8',Q='gquery',eb='gquery.nocache.js',nb='gquery::',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',tc='gwt/clean/clean.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',yc='head',Xb='hosted.html?gquery',xc='href',Sb='ie6',Rb='ie8',Qb='ie9',xb='iframe',ab='img',yb="javascript:''",uc='link',Wb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Pb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',vc='rel',Ob='safari',db='script',Yb='selectingPermutation',R='startup',wc='stylesheet',fb='undefined',Vb='unknown',Ib='user.agent',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}gquery=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,en:1,fr:2};v[Ib]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Jb)!=-1}())return Jb;if(function(){return c.indexOf(Kb)!=-1||function(){if(c.indexOf(Lb)!=-1){return true}if(typeof window[Mb]!=fb){try{var b=new ActiveXObject(Nb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Ob;if(function(){return c.indexOf(Pb)!=-1&&m.documentMode>=9}())return Qb;if(function(){return c.indexOf(Pb)!=-1&&m.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Sb;if(function(){return c.indexOf(Tb)!=-1}())return Ub;return Vb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};gquery.onScriptLoad=function(){if(I){q=true;B()}};gquery.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Xb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Yb});if(!A()){try{G([Zb,Ob],$b);G([_b,Ub],ac);G([Cb,Ub],bc);G([_b,Qb],cc);G([Zb,Jb],dc);G([_b,Jb],ec);G([Zb,Qb],fc);G([_b,Rb],gc);G([Zb,Rb],hc);G([Cb,Jb],ic);G([Cb,Ob],jc);G([Zb,Ub],kc);G([_b,Ob],lc);G([Cb,Sb],mc);G([Zb,Sb],nc);G([_b,Sb],oc);G([Cb,Rb],pc);G([Cb,Qb],qc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(rc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+sc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[tc]){var a=m.createElement(uc);__gwt_stylesLoaded[tc]=a;a.setAttribute(vc,wc);a.setAttribute(xc,s+tc);m.getElementsByTagName(yc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(zc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(zc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:T});m.write(Ac)}
gquery();